<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <AssemblyName>Orbits</AssemblyName>
        <RootNamespace>Orbits</RootNamespace>
        <Nullable>disable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>C:\Users\fiufki\AppData\Roaming\com.kesomannen.gale\lethal-company\profiles\Default\BepInEx\core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx">
            <HintPath>C:\Users\fiufki\AppData\Roaming\com.kesomannen.gale\lethal-company\profiles\Default\BepInEx\core\BepInEx.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
          <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Netcode.Runtime">
            <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Unity.Netcode.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
          <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
